plugins {
    id 'com.android.application'
}

android {
    namespace 'com.htos.apc.placeholder'
    compileSdk 34

    defaultConfig {
        // 这里的包名会被 GitHub Actions 的命令行参数覆盖
        applicationId "com.htos.apc.default"
        minSdk 31
        targetSdk 34
        versionCode 2147483647 // 最大版本号，防止任何形式的覆盖安装
        versionName "99.99.99"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}