plugins {
    id 'com.android.application'
}

android {
    namespace 'com.htos.apc.placeholder'
    compileSdk 34

    defaultConfig {
        // applicationId 会在 GitHub Actions 中动态注入
        applicationId "com.htos.apc.placeholder"
        minSdk 31
        targetSdk 34
        versionCode 2147483647
        versionName "99.99.99"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt')
        }
    }
}